source :gemcutter, :github
gem "json"
gem "rack", "~>1.3.6"
gem "sinatra-flash"
gem "sinatra"
gem "data_mapper"
gem "dm-sqlite-adapter"
gem "dm-postgres-adapter"
gem "haml"
gem "sinatra-subdomain"
gem "tux"
gem "andand"
